# resources/gitleaks-config.toml
title = "Default Gitleaks Config"

[[rules]]
description = "Generic API Key"
regex = '''(?i)api[_-]?key\s*=\s*['"][a-z0-9]{32,}['"]'''
tags = ["key", "api"]

[[rules]]
description = "Generic Password"
regex = '''(?i)password\s*=\s*['"].+['"]'''
tags = ["password"]

[[rules]]
description = "AWS Access Key"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["aws", "key"]

[[rules]]
description = "AWS Secret Key"
regex = '''(?i)aws[_-]?secret[_-]?access[_-]?key\s*=\s*['"][0-9a-zA-Z/+]{40}['"]'''
tags = ["aws", "secret"]
